ingredient_names = [
    'alghe bioluminescenti',
    'amido di stellarion',
    'baccacedro',
    'biscotti della galassia',
    'burrobirra',
    'carne di balena spaziale',
    'carne di drago',
    'carne di kraken',
    'carne di mucca',
    'carne di xenodonte',
    'chocobo wings',
    'cioccorane',
    'cristalli di memoria',
    'cristalli di nebulite',
    'cristalli di sale temporale',
    'erba pipa',
    'essenza di speziaria',
    'essenza di tachioni',
    'essenza di vuoto',
    'farina di nettuno',
    'fibra di sintetex',
    'foglie di mandragora',
    'foglie di nebulosa',
    'frammenti di supernova',
    'frutti del diavolo',
    'funghi dell etere',
    'funghi orbitali',
    'fusilli del vento',
    'ghiaccio di criofenice',
    'gnocchi del crepuscolo',
    'granuli di nebbia arcobaleno',
    'impasto gravitazionale vorticoso',
    'lacrime di andromeda',
    'lacrime di unicorno',
    'latte ',
    'lattuga namecciana',
    'liane di plasmodio',
    'muffa lunare',
    'mycoflora',
    'nduja fritta tanto',
    'nettare di sirena',
    'pane degli abissi',
    'pane di luce',
    'petali di eco',
    'plasma vitale',
    'polvere di crononite',
    'polvere di pulsar',
    'polvere di stelle',
    'radici di gravità',
    'radici di singolarità',
    'ravioli al vaporeon',
    'raviolo traslucido',
    'riso di cassandra',
    'sale temporale',
    'salsa szechuan',
    'sashimi di magikarp',
    'scaglie di stelle',
    'scaglie stellari',
    'shard di materia oscura',
    'shard di prisma stellare',
    'spaghi del sole',
    'spezie melange',
    'spore quantiche',
    'teste di idra',
    'uova di fenice',
    'zucchero cosmico',
]

technique_names = [
'affettamento a pulsazioni quantistiche',
'affumicatura a stratificazione quantica',
'affumicatura polarizzata a freddo iperbarico',
'affumicatura psionica sensoriale',
'affumicatura temporale risonante',
'affumicatura tramite big bang microcosmico',
'amalgamazione sintetica molecolare',
'bollitura entropica sincronizzata',
'bollitura infrasonica armonizzata',
'bollitura termografica a rotazione veloce',
'congelamento bio luminiscente sincronizzato',
'congelamento bioluminiscente sincronico',
'congelazione iperdimensionalmente stratificata',
'cottura a forno dinamico inversionale',
'cottura a vapore con flusso di particelle isoarmoniche',
'cottura a vapore con vapore ecodinamico bilanciato',
'cottura a vapore ecodinamico bilanciato',
'cottura a vapore risonante simbiotico',
'cottura a vapore termocinetica multipla',
'cottura al forno con paradosso temporale cronospeculare',
'cottura con microonde entropiche sincronizzate',
'cottura idrodinamica autoregolante',
'cottura olografica quantum fluttuante',
'cottura sotto la luce di una stella',
'cottura sottovuoto antimateria',
'cottura sottovuoto bioma sintetico',
'cottura sottovuoto frugale energeticamente negativa',
'cottura sottovuoto multirealità collassante',
'cottura sottovuoto pulsar magnetica',
'cristallizzazione temporale reversiva',
'cryotessitura energetica polarizzata',
'decostruzione ancestrale',
'decostruzione atomica a strati energetici',
'decostruzione bio fotonica emotiva',
'decostruzione interdimensionale lovecraftiana',
'decostruzione magnetica risonante',
'ebollizione magneto cinetica pulsante',
'fermentazione psionica energetica',
'fermentazione quantica a strati multiversali',
'fermentazione quantico biometrica',
'fermentazione temporale sincronizzata',
'gravitazione controllata',
'grigliatura a energia stellare',
'grigliatura elettro molecolare a spaziatura variabile',
'grigliatura plasma sintetico risonante',
'grigliatura psionica dinamica ritmica',
'idrocristallizzazione sonora quantistica',
'impasto a campi magnetici dualistici',
'impasto gravitazionale vorticoso',
'incisione elettromagnetica plasmica',
'incisioni elettromagnetiche plasmatiche',
'manipolazione gravitazionale',
'marinatura a infusione gravitazionale',
'marinatura psionica',
'marinatura sotto zero a polarità inversa',
'marinatura temporale sincronizzata',
'marinatura tramite reazioni d antimateria diluite',
'modellatura onirica tetrazionale',
'polarizzazione a freddo iperbarico',
'sferificazione a gravità psionica variabile',
'sferificazione con campi magnetici entropici',
'sferificazione cromatica interdimensionale',
'sferificazione filamentare a molecole vibrazionali',
'sferificazione tramite matrici biofotiche',
'stratificazione quantica',
'surgelamento antimaterico a risonanza inversa',
'taglio a risonanza sonica rigenerativa',
'taglio dimensionale a lame fotofiliche',
'taglio sinaptico biomimetico'
]

technique_groups_names = [
    "marinatura",
    "affumicatura",
    "fermentazione",
    "decostruzione",
    "sferificazione",
    "tecniche di taglio",
    "tecniche di impasto",
    "surgelamento",
    "bollitura",
    "grigliatura",
    "cottura al forno",
    "cottura al vapore",
    "cottura sottovuoto",
    "cottura al salto",
]

restaurant_names = [
    "anima cosmica",
    "armonia universale",
    "cosmica essenza",
    "l infinito sapore",
    "l eco di pandora",
    "l eredita galattica",
    "l essenza dell infinito",
    "il firmamento",
    "l architetto dell universo",
    "l eco dei sapori",
    "l equilibrio quantico",
    "l essenza cosmica",
    "l essenza del multiverso su pandora",
    "l essenza del dune",
    "l essenza di asgard",
    "l etere del gusto",
    "l infinito in un boccone",
    "l oasi delle dune stellari",
    "l universo in cucina",
    "le dimensioni del gusto",
    "le stelle che ballano",
    "le stelle danzanti",
    "ristorante delle dune stellari",
    "ristorante quantico",
    "sala del valhalla",
    "sapore del dune",
    "stelle astrofisiche",
    "stelle dell infinito celestiale",
    "tutti a tarsvola",
    "universo gastronomico di namecc",
]

license_names = [
    "licenza psionica (P)",
    "licenza temporale (t)",
    "licenza gravitazionale (G)",
    "licenza antimateria (e+)",
    "licenza magnetica (Mx)",
    "licenza quantica (Q)",
    "licenza luce (C)",
    "licenza tecnologica LTK",
]

planets_names = [
    "tatooine",
    "asgard",
    "namecc",
    "arrakis",
    "krypton",
    "pandora",
    "cybertron",
    "ego",
    "montressosr",
    "klyntar",
]
