technique_names = [
    "marinatura a infusione gravitazionale",
    "marinatura temporale sincronizzata",
    "marinatura psionica",
    "marinatura tramite reazioni d antimateria diluite",
    "marinatura sotto zero a polarità inversa",
    "affumicatura a stratificazione quantica",
    "affumicatura temporale risonante",
    "affumicatura psionica sensoriale",
    "affumicatura tramite big bang microcosmico",
    "affumicatura polarizzata a freddo iperbarico",
    "fermentazione quantica a strati multiversali",
    "fermentazione temporale sincronizzata",
    "fermentazione psionica energetica",
    "fermentazione tramite singolarità",
    "fermentazione quantico biometrica",
    "decostruzione atomica a strati energetici",
    "decostruzione magnetica risonante",
    "decostruzione bio-fotonica emotiva",
    "decostruzione ancestrale",
    "decostruzione interdimensionale lovercraftiana",
    "sferificazione a gravità psionica variabile",
    "sferificazione filamentare a molecole vibrazionali",
    "sferificazione cromatica interdimensionale",
    "sferificazione con campi magnetici entropici",
    "sferificazione tramite matrici biofotiche",
    "taglio dimensionale a lame fotofilliche",
    "affettamento a pulsazioni quantistiche",
    "taglico sinaptico biomimetico",
    "incisione elettromagnetica plasmica",
    "impasto gravitazionale vorticoso",
    "amalgamazione sintetica molecolare",
    "impasto a campi magnetici dualistici",
    "sinergia elettro-osmotica programmabile",
    "modellatura onirica tetrazionale",
    "cryo-tessitura energetica polarizzata",
    "congelamento bio-luminiscente sincronico",
    "cristallizzazione temporale reversiva",
    "congelazione iperdimensionalmente stratificata",
    "surgelamento antimaterico a risonanza inversa",
    "ebollizione magneto-cinetica pulsante",
    "bollitura infrasonica armonizzata",
    "bollitura termografica a rotazione veloce",
    "bollitura entropica sincronizzata",
    "idro-cristallizzazione sonora quantistica",
    "grigliatura a energia stellare div",
    "grigliatura plasma sintetico risonante",
    "grigliatura elettro-molecolare a spaziatura variabile",
    "grigliatura tachionica refrattaria",
    "grigliatura psionica dinamica ritmica",
    "cottura al forno con paradosso temporale cronospeculare",
    "cottura con microonde entropiche sincronizzate",
    "cottura a forno dinamico inversionale",
    "cottura olografica quantum fluttuante",
    "cottura geomagnetica psicosincronizzata",
    "cottura a vapore risonante simbiotico",
    "cottura idrodinamica autoregolante",
    "cottura sottovuoto antimateria",
    "cottura sottovuoto multirealità collassante",
    "cottura sottovuoto frugale energeticamente negativa",
    "cottura sottovuoto pulsar magnetica",
    "cottura sottovuoto bioma sintetico",
    "saltare in padella big bang termico",
    "saltare in padella realtà energetiche parallele",
    "saltare in padella singolarità inversa",
    "saltare in padella sinergia psionica",
]

technique_groups_names = [
    "marinatura",
    "affumicatura",
    "fermentazione",
    "decostruzione",
    "sferificazione",
    "tecniche di taglio",
    "tecniche di impasto",
    "surgelamento",
    "bollitura",
    "grigliatura",
    "cottura al forno",
    "cottura al vapore",
    "cottura sottovuoto",
    "cottura al salto",
]

restaurant_names = [
    "anima cosmica",
    "armonia universale",
    "cosmica essenza",
    "l infinito sapore",
    "l eco di pandora",
    "l eredita galattica",
    "l essenza dell infinito",
    "il firmamento",
    "l architetto dell universo",
    "l eco dei sapori",
    "l equilibrio quantico",
    "l essenza cosmica",
    "l essenza del multiverso su pandora",
    "l essenza del dune",
    "l essenza di asgard",
    "l etere del gusto",
    "l infinito in un boccone",
    "l oasi delle dune stellari",
    "l universo in cucina",
    "le dimensioni del gusto",
    "le stelle che ballano",
    "le stelle danzanti",
    "ristorante delle dune stellari",
    "ristorante quantico",
    "sala del valhalla",
    "sapore del dune",
    "stelle astrofisiche",
    "stelle dell infinito celestiale",
    "tutti a tarsvola",
    "universo gastronomico di namecc",
]

license_names = [
    "psionica (P)",
    "gravitazionale (G)",
    "antimateria (e+)",
    "magnetica (Mx)",
    "grado tecnologico LTK",
]

planets_names = [
    "tatooine",
    "asgard",
    "namecc",
    "arrakis",
    "krypton",
    "pandora",
    "cybertron",
    "ego",
    "montressosr",
    "klyntar",
]
